keys:
  - &1password age187zlwuajhnq3f3j4f3jxe7sgndpslrw7acuwxe42h93qp7gaegpqdmlccp
  - &fadeoutz age1e04a4mfxymjky0ecrnf3ygkwff2m773ydpzu2ut2jqa8t662wqusyp9c3s
  - &unmusique age1erh5uqmskp79psdkvz6u5fgtxlul3g08uemktllu0syg6lsrjyfsvla0f5
  - &silver-chariot age14kme0qdc89dkmpj558lz3run9y77zjm26awfvfhhzaval06jm4js45qc2g
  - &sisterhood age1x6z9tjpx8t39wr7pusxv70yheefy3uk63levgrr24gfr70pln5ys8f43ep
  - &golden-experience age1gz8kydk5qp8ws7swqjjhunhmyeh5xj8v2lxxv2cudcyn8pr9kesqrj5pzk 
  - &ghostholding age1m6907s82txujxe36d8a7p6frmnw9ndqw0cu49dr5ut6qnk8htuks3du9js
  - &dreamflasher age19yfzje6pm8382xnzy6xj456c3753rvym0p2mp7jztsf62rjc83wskrdqpk
  - &peer2peer age1cp3quktrfdckjza222emh95rd758cvsj777259xqv66ke0l48qvqs7fp7a
  - &pawpatch age1rfysgjptjhvqzmj37u646wp896jypl405g7r7285qc0s8g5r89aqr9rtez
  - &psychoboost age1t3e7cxufz9ljuhf3ltnw8q54tw7fwn3ggwmj6ke5ka5n5cwusuzqfhfcne
  - &experimental-skin age1m09t4l3suvancrvwtu4ylwrqz26xsl85jzx5wyeex33k5f3wxvgq3rrncc
  - &professional-vengeance age13eslnwq6dghrpyhwfym66rpehyd27n54303ps8822wjwexkvpe8qkfxs9r
creation_rules:
  - path_regex: users/.*/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
      - *unmusique
      - *silver-chariot
      - *sisterhood
      - *golden-experience
      - *ghostholding
      - *dreamflasher
      - *peer2peer
      - *pawpatch
      - *psychoboost
      - *experimental-skin
      - *professional-vengeance
  - path_regex: modules/nixos/services/pawpatch/.*$
    key_groups:
      - age:
        - *1password
        - *pawpatch
  - path_regex: modules/nixos/services/grafana/.*$
    key_groups:
      - age:
        - *1password
        - *unmusique
  - path_regex: modules/nixos/services/tailscalesd/.*$
    key_groups:
      - age:
        - *1password
        - *unmusique
  - path_regex: modules/nixos/services/soulseek/.*$
    key_groups:
    - age:
      - *1password
      - *peer2peer
  - path_regex: modules/nixos/services/soularr/.*$
    key_groups:
    - age:
      - *1password
      - *peer2peer
  - path_regex: modules/nixos/services/unpackerr/.*$
    key_groups:
    - age:
      - *1password
      - *peer2peer
  - path_regex: modules/nixos/services/hydra/.*$
    key_groups:
    - age:
      - *1password
      - *silver-chariot
      - *psychoboost
  - path_regex: modules/nixos/services/step-ca/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
  - path_regex: modules/nixos/services/openbao/.*$
    key_groups:
    - age:
      - *1password
      - *unmusique
  - path_regex: machines/fadeoutz/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
  - path_regex: machines/nixos/sisterhood/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *sisterhood
  - path_regex: machines/nixos/unmusique/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *unmusique
  - path_regex: machines/nixos/silver-chariot/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *silver-chariot
  - path_regex: machines/nixos/peer2peer/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *peer2peer
  - path_regex: machines/nixos/psychoboost/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *psychoboost
